### PR TITLE
See commit comments

### PR DESCRIPTION
**Pull request by auroraaxela**

### CODE REVIEW

**Comment by fred15** [comment]
SuperHoneyPot/honeypot/honeypot.py loads the plug-ins already..... get on slack
and explain the difference between the two

On Thu, Jan 28, 2016 at 2:08 AM, auroraaxela < notifications@github.com [notifications@github.com] > wrote:

---

YOU CAN VIEW, COMMENT ON, OR MERGE THIS PULL REQUEST ONLINE AT:
https://github.com/redragonx/SuperHoneyPot/pull/7
[https://github.com/redragonx/SuperHoneyPot/pull/7]

COMMIT SUMMARY
- Created loader to load the plugins. Still needs some fine tuning, but it is
  close. Moved bindings (Stephen) into init functions. Source path needs
  adjustment for other systems.
- Created loader to load the plugins. Still needs some fine tuning, but it is
  close. Moved bindings (Stephen) into init functions. Source path needs
  adjustment for other systems.

FILE CHANGES
- M honeypot/src/http_reader.py
  [https://github.com/redragonx/SuperHoneyPot/pull/7/files#diff-0](19)
- M honeypot/src/https_reader.py
  [https://github.com/redragonx/SuperHoneyPot/pull/7/files#diff-1](18)
- M honeypot/src/ssh_plugin.py
  [https://github.com/redragonx/SuperHoneyPot/pull/7/files#diff-2](0)
- M honeypot/src/telnet_reader.py
  [https://github.com/redragonx/SuperHoneyPot/pull/7/files#diff-3](19)
- A honeypotLoader.py
  [https://github.com/redragonx/SuperHoneyPot/pull/7/files#diff-4](0)

PATCH LINKS:
- https://github.com/redragonx/SuperHoneyPot/pull/7.patch
  [https://github.com/redragonx/SuperHoneyPot/pull/7.patch]
- https://github.com/redragonx/SuperHoneyPot/pull/7.diff
  [https://github.com/redragonx/SuperHoneyPot/pull/7.diff]

**Comment by fred15** [comment]
Actually nvm ya'll can explain tomorrow in class, I'll take it for now though
seems like we may have coded the same thing in different ways

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.91&pv=5.0&source=email_footer_2] On Thu, Jan 28, 2016 at 2:08 AM, auroraaxela < notifications@github.com [notifications@github.com] > wrote:

---

YOU CAN VIEW, COMMENT ON, OR MERGE THIS PULL REQUEST ONLINE AT:
https://github.com/redragonx/SuperHoneyPot/pull/7
[https://github.com/redragonx/SuperHoneyPot/pull/7]

COMMIT SUMMARY
- Created loader to load the plugins. Still needs some fine tuning, but it is
  close. Moved bindings (Stephen) into init functions. Source path needs
  adjustment for other systems.
- Created loader to load the plugins. Still needs some fine tuning, but it is
  close. Moved bindings (Stephen) into init functions. Source path needs
  adjustment for other systems.

FILE CHANGES
- M honeypot/src/http_reader.py
  [https://github.com/redragonx/SuperHoneyPot/pull/7/files#diff-0](19)
- M honeypot/src/https_reader.py
  [https://github.com/redragonx/SuperHoneyPot/pull/7/files#diff-1](18)
- M honeypot/src/ssh_plugin.py
  [https://github.com/redragonx/SuperHoneyPot/pull/7/files#diff-2](0)
- M honeypot/src/telnet_reader.py
  [https://github.com/redragonx/SuperHoneyPot/pull/7/files#diff-3](19)
- A honeypotLoader.py
  [https://github.com/redragonx/SuperHoneyPot/pull/7/files#diff-4](0)

PATCH LINKS:
- https://github.com/redragonx/SuperHoneyPot/pull/7.patch
  [https://github.com/redragonx/SuperHoneyPot/pull/7.patch]
- https://github.com/redragonx/SuperHoneyPot/pull/7.diff
  [https://github.com/redragonx/SuperHoneyPot/pull/7.diff]

**Comment by auroraaxela** [comment]
Never saw that honeypot.py file... but I imagine it would work. You're right, maybe two ways of doing the same thing. Do we need those to be threads since each connection is going to spawn a new thread anyways? We'll talk tomorrow.

**Comment by redragonx** [comment]
We'll hold up on this for now.

**Comment by redragonx** [comment]
@fred15 

https://github.com/redragonx/SuperHoneyPot/tree/auroraaxela-master

I made a new branch for you.

**Comment by fred15** [comment]
thanks Stephen.

I keep getting this error with the code. I've changed the path to be the
path to my folder but then this kept coming up now:

D:\programs\Python27\python.exe
D:/Dropbox/SuperHoneyPot/honeypot/honeypotLoader.py
Traceback (most recent call last):
  File "D:/Dropbox/SuperHoneyPot/honeypot/honeypotLoader.py", line 24, in
<module>
    print 'Plugin %s loaded. ' % plugins[x]
  File "D:/Dropbox/SuperHoneyPot/honeypot/honeypotLoader.py", line 15, in
**init**

  File "D:/Dropbox/SuperHoneyPot/honeypot/honeypotLoader.py", line 21, in
load
    f, filename, desc = imp.find_module(plugins[x], location)
AttributeError: 'module' object has no attribute 'plugin_main'

Process finished with exit code 1

no idea what or where plugin_main is

**Comment by redragonx** [comment]
Closing as I will wait for Chris to finish his loader.

**Pull request closed without merging**
