### PR TITLE
Updating List

### PR DESCRIPTION
**Pull request by WDKing**

### CODE REVIEW

**Comment by redragonx** [comment]
what did you add/change?

**Comment by WDKing** [comment]
I added the requirements, and detailed design in the extras. Then deleted
the detailed_design branch without pushing anything, and pulled into my
name branch.

**Comment by redragonx** [comment]
You didn't seem to create the PR correctly, the master already has these file changes. It's just showing fred's, and the other's changes. 

Plus you don't need to merge to update your branches, so I'm bit confused as what actual changes you made.

**Comment by redragonx** [comment]
This branch is 14 commits behind master. git pull origin master from your William to get a copy of current code. Closing PR as the branches are being updated without merging.

**Pull request closed without merging**
